# Generated by Django 5.2.12 on 2026-03-12 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recepient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=32, verbose_name='Имя получателя')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг получателя')),
            ],
            options={
                'verbose_name': 'получатель',
                'verbose_name_plural': 'Получатели',
            },
        ),
        migrations.CreateModel(
            name='Postcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path_image', models.ImageField(blank=True, upload_to='postcards', verbose_name='Фотография')),
                ('description', models.TextField(max_length=256, verbose_name='Описание')),
                ('recepient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.recepient')),
            ],
            options={
                'verbose_name': 'Открытка',
                'verbose_name_plural': 'Открытки',
            },
        ),
    ]
